
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NextAuthProvider from "./providers/NextAuthProvider";
import QueryProvider from "./providers/QueryPrivder";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Toaster position="bottom-center" />
        <QueryProvider >
          <NextAuthProvider>
            <ThemeProvider attribute="class" defaultTheme="dark" themes={["light", "dark"]} enableSystem disableTransitionOnChange >
              {children}
            </ThemeProvider>
          </NextAuthProvider>
        </QueryProvider>
      </body>
    </html>


  );
}
